services:
  ux-users:
    image: ${DOCKER_REGISTRY_NAME}/experience-users:0.0.1-SNAPSHOT
    container_name: ux-users
    restart: always
    depends_on:
      - redis
    environment:
      SPRING_PROFILE: compose
    networks:
      - gaia_backend
    ports:
      - "8080:8080"
  sp-users:
    image: ${DOCKER_REGISTRY_NAME}/support-users:0.0.1-SNAPSHOT
    container_name: sp-users
    restart: always
    depends_on:
      - postgres
    environment:
      SPRING_PROFILE: compose
    ports:
      - "8081:8080" # Just for testing purposes, this container doesn't need to be exposed
    networks:
      - gaia_backend

  postgres:
    image: postgres:17
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: gaia-pet
    networks:
      - gaia_backend

    ports:
      - "5433:5432"

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    networks:
      - gaia_backend
    ports:
      - "6379:6379"


networks:
  gaia_backend:
    driver: bridge
